name: CPP AKS Module
trigger: none
pr:
  - main

resources:
  repositories:
    - repository: cppAzureDevOpsTemplates
      type: github
      name: hmcts/cpp-azure-devops-templates
      endpoint: 'hmcts'

extends:
  template: pipelines/terratest.yaml@cppAzureDevOpsTemplates
  parameters:
    agentPool: "MDV-ADO-AGENTS-01"
    spnCredentialsVarGroup: "terratest-app-registration"
    azureServiceConnection: "ado_nonlive_service_principal_lab"
    terratestTimeout: "60"
    tfversion: 1.0.1
